# Extract all 196 ESS questions from the PDF content
ess_questions = [
    # Environmental Science and Sustainability Questions 1-50
    {"id": 1, "question": "Which of the following is not an abiotic component of an ecosystem?", "options": ["Bacteria", "Temperature", "Soil", "Water"], "correct": 0},
    {"id": 2, "question": "In the 10% law of energy flow, if plants capture 10,000 kcal of energy, how much will be available to herbivores?", "options": ["1000 kcal", "10 kcal", "1,000 kcal", "5,000 kcal"], "correct": 0},
    {"id": 3, "question": "Which of the following is a biotic component of an ecosystem?", "options": ["Fungi", "Light", "Temperature", "Water"], "correct": 0},
    {"id": 4, "question": "The primary source of energy driving ecological cycles is:", "options": ["Solar radiation", "Wind", "Soil minerals", "Water cycle"], "correct": 0},
    {"id": 5, "question": "The second law of thermodynamics explains why:", "options": ["Energy transfer between trophic levels is inefficient", "Energy can be recycled in ecosystems", "Nutrients are lost in food chains", "Decomposers cannot recycle minerals"], "correct": 0},
    {"id": 6, "question": "Which ecosystem has the highest net primary productivity per unit area?", "options": ["Tropical rainforest", "Coral reefs", "Open ocean", "Desert scrub"], "correct": 0},
    {"id": 7, "question": "The pyramids of number in a grassland ecosystem is usually:", "options": ["Upright", "Inverted", "Spindle-shaped", "Irregular"], "correct": 0},
    {"id": 8, "question": "Which one of the following statements is false?", "options": ["Decomposers are absent in aquatic ecosystems", "Energy flow in an ecosystem is unidirectional", "Matter cycles within an ecosystem", "Herbivores are primary consumers"], "correct": 0},
    {"id": 9, "question": "A self-sustaining natural ecosystem is:", "options": ["Pond", "Agricultural field", "Aquarium", "Garden"], "correct": 0},
    {"id": 10, "question": "Which process in the ecosystem directly connects biotic and abiotic components?", "options": ["Photosynthesis", "Predation", "Parasitism", "Competition"], "correct": 0},
    {"id": 11, "question": "Which ecological pyramid can never be inverted?", "options": ["Pyramid of energy", "Pyramid of biomass", "Pyramid of number", "All pyramids"], "correct": 0},
    {"id": 12, "question": "In a forest ecosystem, primary consumers are:", "options": ["Herbivores", "Carnivores", "Decomposers", "Omnivores"], "correct": 0},
    {"id": 13, "question": "The most stable ecosystem is:", "options": ["Ocean", "Desert", "Forest", "Grassland"], "correct": 0},
    {"id": 14, "question": "Which of the following represents the correct sequence of energy flow?", "options": ["Sun → Producer → Primary consumer → Secondary consumer → Decomposer", "Sun → Producer → Secondary consumer → Primary consumer → Decomposer", "Producer → Sun → Primary consumer → Secondary consumer → Decomposer", "Sun → Primary consumer → Producer → Decomposer → Secondary consumer"], "correct": 0},
    {"id": 15, "question": "Which term refers to the maximum energy available to a consumer population after respiration losses of producers?", "options": ["Net primary productivity (NPP)", "Gross primary productivity (GPP)", "Secondary productivity", "Biomass productivity"], "correct": 0},
    {"id": 16, "question": "In ecological succession, the first species to colonize a barren area are called:", "options": ["Pioneer species", "Climax community", "Secondary species", "Keystone species"], "correct": 0},
    {"id": 17, "question": "The ecosystem where decomposers play the most significant role in recycling nutrients is:", "options": ["Forest floor", "Desert", "Open ocean", "Tundra"], "correct": 0},
    {"id": 18, "question": "Which factor limits energy flow efficiency between trophic levels?", "options": ["Heat loss through respiration", "Abundance of producers", "Herbivore population size", "Nutrient cycling"], "correct": 0},
    {"id": 19, "question": "The sequence of organisms through which energy flows in an ecosystem is called:", "options": ["Food chain", "Food web", "Food pyramid", "Ecological succession"], "correct": 0},
    {"id": 20, "question": "Which of the following represents a grazing food chain?", "options": ["Grass → Grasshopper → Frog → Snake", "Dead plants → Fungi → Bacteria", "Algae → Zooplankton → Fish", "Lion → Hyena → Vulture"], "correct": 0},
    {"id": 21, "question": "The interconnected network of food chains in an ecosystem is known as:", "options": ["Food web", "Food chain", "Trophic level", "Food pyramid"], "correct": 0},
    {"id": 22, "question": "In a food chain, the green plants are always:", "options": ["Producers", "Primary consumers", "Secondary consumers", "Decomposers"], "correct": 0},
    {"id": 23, "question": "The largest artificial ecosystem on Earth is:", "options": ["Agricultural fields", "Aquarium", "Reservoirs", "Urban cities"], "correct": 0},
    {"id": 24, "question": "Which ecological pyramid is always upright?", "options": ["Pyramid of energy", "Pyramid of biomass", "Pyramid of number", "All pyramids"], "correct": 0},
    {"id": 25, "question": "In a food pyramid, the largest number of organisms is found at the:", "options": ["Producer level", "Tertiary consumer level", "Secondary consumer level", "Top carnivore level"], "correct": 0},
    {"id": 26, "question": "Which of the following organisms occupies the highest trophic level in a food chain?", "options": ["Top carnivores", "Herbivores", "Producers", "Decomposers"], "correct": 0},
    {"id": 27, "question": "In a detritus food chain, the primary source of energy is:", "options": ["Dead organic matter", "Sunlight", "Producers", "Herbivores"], "correct": 0},
    {"id": 28, "question": "Which food chain correctly shows the flow of energy in a pond ecosystem?", "options": ["Phytoplankton → Zooplankton → Small fish → Large fish", "Zooplankton → Phytoplankton → Small fish → Large fish", "Large fish → Small fish → Zooplankton → Phytoplankton", "Phytoplankton → Small fish → Zooplankton → Large fish"], "correct": 0},
    {"id": 29, "question": "Why does the pyramid of energy never get inverted?", "options": ["Energy decreases at each trophic level", "Biomass is always constant", "Number of organisms increases at higher levels", "Energy flows in cycles"], "correct": 0},
    {"id": 30, "question": "In a food web, organisms that feed on both plants and animals are called:", "options": ["Omnivores", "Herbivores", "Carnivores", "Producers"], "correct": 0},
    {"id": 31, "question": "Which ecological pyramid may sometimes appear inverted?", "options": ["Pyramid of biomass", "Pyramid of energy", "Pyramid of numbers", "All pyramids"], "correct": 0},
    {"id": 32, "question": "The amount of energy transferred from one trophic level to the next is approximately:", "options": ["10%", "1%", "25%", "50%"], "correct": 0},
    {"id": 33, "question": "The lion in a grassland food chain is an example of:", "options": ["Tertiary consumer", "Primary consumer", "Secondary consumer", "Producer"], "correct": 0},
    {"id": 34, "question": "The flow of energy in an ecosystem is always:", "options": ["Linear", "Cyclic", "Multidirectional", "Reversible"], "correct": 0},
    {"id": 35, "question": "Food webs provide more stability to the ecosystem than food chains because:", "options": ["They offer alternative pathways for energy flow", "They are shorter than food chains", "They depend only on producers", "They have fewer trophic levels"], "correct": 0},
    {"id": 36, "question": "The variety of life forms at all levels of biological organization is called:", "options": ["Biodiversity", "Ecology", "Ecosystem", "Biomass"], "correct": 0},
    {"id": 37, "question": "Which type of biodiversity refers to variations within the same species?", "options": ["Genetic diversity", "Species diversity", "Ecosystem diversity", "Habitat diversity"], "correct": 0},
    {"id": 38, "question": "Which type of biodiversity refers to the variety of species in a given area?", "options": ["Species diversity", "Genetic diversity", "Ecosystem diversity", "Population diversity"], "correct": 0},
    {"id": 39, "question": "Which type of biodiversity refers to different habitats, biotic communities, and ecological processes?", "options": ["Ecosystem diversity", "Genetic diversity", "Species diversity", "Habitat diversity"], "correct": 0},
    {"id": 40, "question": "India is recognized as a mega-diversity nation because:", "options": ["It has a wide variety of species and ecosystems", "It has the largest forests", "It has only endemic species", "It has maximum wetlands"], "correct": 0},
    {"id": 41, "question": "The Himalaya and Indo-Burma regions are examples of:", "options": ["Biodiversity hotspots", "Genetic reserves", "Wildlife sanctuaries", "Ex-situ conservation sites"], "correct": 0},
    {"id": 42, "question": "Which of the following is a consumptive use value of biodiversity?", "options": ["Fuel wood", "Aesthetic value", "Recreational value", "Cultural value"], "correct": 0},
    {"id": 43, "question": "Which of the following is a non-consumptive use value of biodiversity?", "options": ["Ecotourism", "Food", "Timber", "Medicine"], "correct": 0},
    {"id": 44, "question": "The greatest threat to biodiversity is:", "options": ["Habitat loss", "Ecotourism", "Medicinal plant use", "Ex-situ conservation"], "correct": 0},
    {"id": 45, "question": "Which of the following ecosystems has the highest productivity?", "options": ["Estuary", "Desert", "Grassland", "Tundra"], "correct": 0},
    {"id": 46, "question": "The species found only in a particular area and nowhere else are called:", "options": ["Endemic species", "Endangered species", "Exotic species", "Vulnerable species"], "correct": 0},
    {"id": 47, "question": "Which of the following is NOT a threat to biodiversity?", "options": ["Ex-situ conservation", "Poaching of wildlife", "Habitat destruction", "Man-wildlife conflict"], "correct": 0},
    {"id": 48, "question": "Which biodiversity hotspot in India is richest in endemism?", "options": ["Indo-Burma region", "Himalaya", "Sundarbans", "Gangetic plains"], "correct": 0},
    {"id": 49, "question": "Which of the following represents the option value of biodiversity?", "options": ["Future potential use of biodiversity", "Current use of biodiversity", "Cultural value of biodiversity", "Spiritual value of biodiversity"], "correct": 0},
    {"id": 50, "question": "The Western Ghats are a hotspot of biodiversity because they:", "options": ["Harbor a large number of endemic species", "Are densely populated", "Are used for agriculture", "Are rich in minerals"], "correct": 0},
]

# Continue with questions 51-100
ess_questions_51_100 = [
    {"id": 51, "question": "Which international agreement focuses on the conservation of biodiversity?", "options": ["Convention on Biological Diversity (CBD)", "Kyoto Protocol", "Paris Agreement", "Montreal Protocol"], "correct": 0},
    {"id": 52, "question": "Which Indian state is part of both the Indo-Burma and Himalaya hotspots?", "options": ["Arunachal Pradesh", "Rajasthan", "Kerala", "Maharashtra"], "correct": 0},
    {"id": 53, "question": "Which of the following is an example of in-situ conservation of biodiversity?", "options": ["National park", "Zoo", "Seed bank", "Botanical garden"], "correct": 0},
    {"id": 54, "question": "The IUCN Red List provides information about:", "options": ["Conservation status of species", "Types of ecosystems", "Levels of biodiversity", "Agricultural practices"], "correct": 0},
    {"id": 55, "question": "The ethical value of biodiversity refers to:", "options": ["The right of all species to exist", "Commercial use of species", "Food and medicine", "Recreation"], "correct": 0},
    {"id": 56, "question": "Which level of consumers directly depends on green plants for energy?", "options": ["Primary consumers", "Secondary consumers", "Tertiary consumers", "Quaternary consumers"], "correct": 0},
    {"id": 57, "question": "Overexploitation of resources primarily leads to:", "options": ["Loss of biodiversity", "Increase in biodiversity", "Stabilization of ecosystems", "Formation of new species"], "correct": 0},
    {"id": 58, "question": "The term 'Ecosystem' was first coined by:", "options": ["A.G. Tansley", "Charles Darwin", "Ernst Haeckel", "Odum"], "correct": 0},
    {"id": 59, "question": "The word 'Ecology' was first coined by:", "options": ["Ernst Haeckel", "A.G. Tansley", "Charles Elton", "Linnaeus"], "correct": 0},
    {"id": 60, "question": "The root word 'Eco' in Ecology and Ecosystem is derived from Greek 'Oikos', meaning:", "options": ["House or dwelling place", "Environment", "Organism", "Nature"], "correct": 0},
    {"id": 61, "question": "Ecology is mainly concerned with:", "options": ["Interactions between organisms and their environment", "Evolution of organisms", "Genetic variations", "Geological processes"], "correct": 0},
    {"id": 62, "question": "The relationship between Ecology and Ecosystem can be defined as:", "options": ["Ecology studies interactions, Ecosystem is the structural and functional unit", "Ecosystem creates species, Ecology destroys them", "Ecology is smaller than an Ecosystem", "They are unrelated concepts"], "correct": 0},
    {"id": 63, "question": "In an ecosystem, which organisms return nutrients back to the soil?", "options": ["Decomposers", "Producers", "Primary consumers", "Secondary consumers"], "correct": 0},
    {"id": 64, "question": "Which one of the following is a man-made/artificial ecosystem?", "options": ["Aquarium", "Forest", "Pond", "Grassland"], "correct": 0},
    {"id": 65, "question": "The source of all energy in an ecosystem is:", "options": ["Sunlight", "Water", "Oxygen", "Soil nutrients"], "correct": 0},
    {"id": 66, "question": "Which organization monitors environmental issues globally?", "options": ["UNEP", "WHO", "UNICEF", "UNESCO"], "correct": 0},
    {"id": 67, "question": "Which term refers to the variety of life on Earth?", "options": ["Biodiversity", "Ecology", "Habitat", "Conservation"], "correct": 0},
    {"id": 68, "question": "What does the 3Rs principle stand for?", "options": ["Reduce, Reuse, Recycle", "Rebuild, Reuse, Reboot", "Reduce, Recycle, Recover", "Recycle, Reuse, Repeat"], "correct": 0},
    {"id": 69, "question": "The Environment (Protection) Act was enacted in which year?", "options": ["1986", "1972", "1992", "2000"], "correct": 0},
    {"id": 70, "question": "World Environment Day is celebrated on:", "options": ["June 5", "April 22", "December 1", "March 21"], "correct": 0},
    {"id": 71, "question": "The Environment (Protection) Act was enacted after which global event?", "options": ["Bhopal Gas Tragedy", "Rio Earth Summit", "Kyoto Protocol", "Stockholm Conference"], "correct": 0},
    {"id": 72, "question": "The most common indicator of water pollution is:", "options": ["Dissolved Oxygen", "pH", "Salinity", "Conductivity"], "correct": 0},
    {"id": 73, "question": "Which parameter indicates the amount of oxygen required by microorganisms to decompose organic matter?", "options": ["BOD", "COD", "DO", "TOC"], "correct": 0},
    {"id": 74, "question": "COD in water represents:", "options": ["Oxygen required to oxidize organic & inorganic matter chemically", "Oxygen used by microorganisms", "Oxygen dissolved in water", "Oxygen consumed by fish"], "correct": 0},
    {"id": 75, "question": "Which type of waste increases BOD levels in water?", "options": ["Organic waste", "Plastic waste", "Heavy metals", "Salts"], "correct": 0},
    {"id": 76, "question": "High BOD in a river indicates:", "options": ["Heavy organic pollution", "Good water quality", "High dissolved oxygen", "Low organic load"], "correct": 0},
    {"id": 77, "question": "Dissolved Oxygen (DO) is essential for:", "options": ["Aquatic life survival", "Maintaining pH", "Reducing hardness", "Neutralizing toxins"], "correct": 0},
    {"id": 78, "question": "Typical BOD of clean drinking water is:", "options": ["< 1 mg/L", "10 mg/L", "50 mg/L", "100 mg/L"], "correct": 0},
    {"id": 79, "question": "When sewage is discharged into water, DO levels:", "options": ["Decrease", "Increase", "Remain constant", "Become zero immediately"], "correct": 0},
    {"id": 80, "question": "The presence of high COD compared to BOD indicates:", "options": ["Presence of toxic pollutants", "Only biodegradable waste", "No pollution", "Absence of chemicals"], "correct": 0},
    {"id": 81, "question": "Major source of organic pollution in rivers is:", "options": ["Domestic sewage", "Industrial salts", "Thermal pollution", "Mining"], "correct": 0},
    {"id": 82, "question": "In a polluted river, DO levels are usually:", "options": ["< 4 mg/L", "8–10 mg/L", "12–15 mg/L", "> 20 mg/L"], "correct": 0},
    {"id": 83, "question": "Eutrophication of lakes is mainly due to:", "options": ["Excess nutrients (N, P)", "High DO", "Low COD", "Neutral pH"], "correct": 0},
    {"id": 84, "question": "Which unit is used to express BOD and COD?", "options": ["mg/L", "g/L", "ppm", "%"], "correct": 0},
    {"id": 85, "question": "DO in water is replenished mainly by:", "options": ["Photosynthesis & Atmospheric diffusion", "Sedimentation", "Decomposition", "Oxidation"], "correct": 0},
    {"id": 86, "question": "The self-purification of rivers is due to:", "options": ["Re-aeration & microbial degradation", "COD increase", "Acidification", "Evaporation"], "correct": 0},
    {"id": 87, "question": "Which is more rapid as a test for pollution?", "options": ["COD test", "BOD test", "DO test", "pH test"], "correct": 0},
    {"id": 88, "question": "If BOD = 300 mg/L in wastewater, the water quality is:", "options": ["Highly polluted", "Clean", "Moderately polluted", "Potable"], "correct": 0},
    {"id": 89, "question": "The most important parameter for measuring organic pollution load is:", "options": ["BOD", "Hardness", "Turbidity", "Alkalinity"], "correct": 0},
    {"id": 90, "question": "The major pollutant responsible for acid rain is:", "options": ["SO₂", "CO₂", "O₃", "CH₄"], "correct": 0},
    {"id": 91, "question": "Photochemical smog is mainly caused by:", "options": ["NOx and hydrocarbons", "CO₂ and SO₂", "CO and CO₂", "O₂ and N₂"], "correct": 0},
    {"id": 92, "question": "The Air Quality Index (AQI) indicates:", "options": ["Level of air pollution affecting health", "Temperature variation", "Rainfall prediction", "Wind speed"], "correct": 0},
    {"id": 93, "question": "The most harmful type of particulate matter for human lungs is:", "options": ["PM2.5", "PM10", "PM100", "Dust particles > 100 µm"], "correct": 0},
    {"id": 94, "question": "The disease 'Black lung disease' is associated with:", "options": ["Coal miners (particulates)", "Tobacco smoke", "Lead poisoning", "Asbestos"], "correct": 0},
    {"id": 95, "question": "Ozone in the stratosphere is:", "options": ["Beneficial, absorbs UV rays", "Harmful, greenhouse gas", "Cause of smog", "A heavy metal"], "correct": 0},
    {"id": 96, "question": "Ozone in the troposphere is:", "options": ["Harmful air pollutant", "Protective layer", "Neutral gas", "Not significant"], "correct": 0},
    {"id": 97, "question": "Carbon monoxide pollution mainly affects:", "options": ["Oxygen transport in blood", "Nervous system", "Vision", "Bones"], "correct": 0},
    {"id": 98, "question": "The main pollutant from automobiles is:", "options": ["Carbon monoxide", "Sulphur dioxide", "Methane", "CFCs"], "correct": 0},
    {"id": 99, "question": "Which gas causes respiratory irritation and bronchitis?", "options": ["SO₂", "CO₂", "CH₄", "H₂"], "correct": 0},
    {"id": 100, "question": "Which of the following is a greenhouse gas?", "options": ["CO₂", "N₂", "Ar", "O₂"], "correct": 0},
]

print(f"Questions 1-50: {len(ess_questions)}")
print(f"Questions 51-100: {len(ess_questions_51_100)}")

# Let me continue with the remaining questions to reach 196
total_so_far = len(ess_questions) + len(ess_questions_51_100)
print(f"Total questions so far: {total_so_far}")
print("Need to add", 196 - total_so_far, "more questions")