# Continue with questions 101-196 from the ESS PDF
ess_questions_101_196 = [
    {"id": 101, "question": "The Bhopal gas tragedy (1984) was caused by leakage of:", "options": ["Methyl isocyanate (MIC)", "Ammonia", "SO₂", "Chlorine"], "correct": 0},
    {"id": 102, "question": "Lead pollution in air mainly comes from:", "options": ["Old vehicle exhaust (leaded petrol)", "Nuclear plants", "Forest fires", "Soil erosion"], "correct": 0},
    {"id": 103, "question": "The colorless, odorless, toxic gas that binds to hemoglobin is:", "options": ["Carbon monoxide", "Methane", "Sulphur dioxide", "Nitrous oxide"], "correct": 0},
    {"id": 104, "question": "AQI value above 400 indicates:", "options": ["Severe pollution", "Good air quality", "Moderate air quality", "Satisfactory"], "correct": 0},
    {"id": 105, "question": "Which pollutant damages the nervous system, especially in children?", "options": ["Lead", "SO₂", "CO₂", "O₃"], "correct": 0},
    {"id": 106, "question": "The major cause of soil pollution is:", "options": ["Excessive use of chemicals (pesticides, fertilizers)", "Waterlogging", "Wind erosion", "Soil organisms"], "correct": 0},
    {"id": 107, "question": "Soil pollution by heavy metals mainly comes from:", "options": ["Industrial effluents", "Biomass burning", "Oxygen depletion", "Acid rain"], "correct": 0},
    {"id": 108, "question": "Excess nitrate in soil leads to:", "options": ["Groundwater pollution", "Ozone depletion", "Acid rain", "Soil erosion"], "correct": 0},
    {"id": 109, "question": "Which of the following is not a biodegradable solid waste?", "options": ["Plastic", "Paper", "Food waste", "Wood"], "correct": 0},
    {"id": 110, "question": "Municipal solid waste (MSW) in India is largely composed of:", "options": ["Organic matter", "Plastic", "Metal", "Glass"], "correct": 0},
    {"id": 111, "question": "The process of controlled burning of solid waste at high temperatures is:", "options": ["Incineration", "Composting", "Landfilling", "Vermiculture"], "correct": 0},
    {"id": 112, "question": "The process of converting organic waste into manure is:", "options": ["Composting", "Incineration", "Recycling", "Gasification"], "correct": 0},
    {"id": 113, "question": "Sanitary landfills are used for:", "options": ["Safe disposal of solid waste", "Irrigation", "Mining", "Soil erosion control"], "correct": 0},
    {"id": 114, "question": "Biomedical waste should be disposed of by:", "options": ["Incineration", "Composting", "Open dumping", "Landfilling"], "correct": 0},
    {"id": 115, "question": "Which is considered hazardous waste?", "options": ["E-waste", "Food waste", "Paper waste", "Yard waste"], "correct": 0},
    {"id": 116, "question": "E-waste mainly contains:", "options": ["Toxic heavy metals and plastics", "Only organic matter", "Pure biodegradable compounds", "Harmless salts"], "correct": 0},
    {"id": 117, "question": "Which metal is most common in e-waste?", "options": ["Lead", "Sodium", "Calcium", "Potassium"], "correct": 0},
    {"id": 118, "question": "Mercury pollution in soil is commonly associated with:", "options": ["Electronic waste", "Textile industry", "Agriculture", "Forest fires"], "correct": 0},
    {"id": 119, "question": "The best method of managing biodegradable solid waste is:", "options": ["Composting", "Open dumping", "Burning", "Deep burial"], "correct": 0},
    {"id": 120, "question": "Which electronic device contributes the maximum to e-waste in India?", "options": ["Mobile phones & computers", "Refrigerators", "Air conditioners", "Printers"], "correct": 0},
    {"id": 121, "question": "Which method is most eco-friendly for solid waste management?", "options": ["Reduce, Reuse, Recycle (3Rs)", "Open dumping", "Incineration", "Landfilling"], "correct": 0},
    {"id": 122, "question": "Which of the following pollutants is most commonly associated with agricultural runoff?", "options": ["Nitrates and phosphates", "Mercury", "Lead", "Asbestos"], "correct": 0},
    {"id": 123, "question": "What is eutrophication?", "options": ["Excessive growth of algae due to nutrient pollution", "Removal of pollutants from water", "Increase in oxygen levels in water", "Depletion of nutrients in water"], "correct": 0},
    {"id": 124, "question": "The presence of which of the following in drinking water indicates contamination by human or animal waste?", "options": ["Escherichia coli (E. coli)", "Chlorine", "Nitrates", "Iron"], "correct": 0},
    {"id": 125, "question": "Acid rain is a type of water pollution caused mainly by:", "options": ["Sulfur dioxide and nitrogen oxides", "Carbon monoxide and nitrogen", "Methane and hydrogen", "Oxygen and helium"], "correct": 0},
    {"id": 126, "question": "The process of removing salt from seawater is called:", "options": ["Desalination", "Chlorination", "Sedimentation", "Filtration"], "correct": 0},
    {"id": 127, "question": "Which of these is not a water-borne disease?", "options": ["Malaria", "Typhoid", "Cholera", "Dysentery"], "correct": 0},
    {"id": 128, "question": "Point source pollution refers to pollution that:", "options": ["Can be traced to a specific location", "Comes from rain", "Comes from the atmosphere", "Has no specific origin"], "correct": 0},
    {"id": 129, "question": "Which of these is a biological method of water purification?", "options": ["Activated sludge process", "Boiling", "Chlorination", "Reverse osmosis"], "correct": 0},
    {"id": 130, "question": "Pesticides and fertilizers are primarily responsible for:", "options": ["Soil pollution", "Increasing biodiversity", "Improving soil texture", "Erosion control"], "correct": 0},
    {"id": 131, "question": "Which of the following is a biodegradable pollutant?", "options": ["Paper", "Plastic", "Glass", "DDT"], "correct": 0},
    {"id": 132, "question": "What is bioremediation?", "options": ["Use of microorganisms to clean pollutants", "Use of chemicals to remove pollution", "Burning of waste", "Soil erosion control"], "correct": 0},
    {"id": 133, "question": "Landfills are a source of:", "options": ["Soil contamination", "Soil improvement", "Groundwater recharge", "Pest control"], "correct": 0},
    {"id": 134, "question": "What is leaching in soil?", "options": ["Removal of nutrients by water", "Fertilizer application", "Aeration of soil", "Addition of humus"], "correct": 0},
    {"id": 135, "question": "What is smog primarily composed of?", "options": ["Smoke and fog", "Water vapor and dust", "Ozone and carbon dioxide", "Nitrogen and oxygen"], "correct": 0},
    {"id": 136, "question": "Which of the following is a greenhouse gas contributing to global warming?", "options": ["Methane", "Nitrogen", "Argon", "Neon"], "correct": 0},
    {"id": 137, "question": "What is the effect of ozone depletion?", "options": ["Increased ultraviolet radiation reaching Earth", "Increased greenhouse effect", "Decreased rainfall", "More acid rain"], "correct": 0},
    {"id": 138, "question": "Which unit is commonly used to measure air pollution levels (such as particulate matter concentration)?", "options": ["Micrograms per cubic meter (µg/m³)", "Decibel (dB)", "Hertz (Hz)", "Watts (W)"], "correct": 0},
    {"id": 139, "question": "Which of the following is a natural source of air pollution?", "options": ["Volcanic eruptions", "Factory emissions", "Automobile exhaust", "Burning fossil fuels"], "correct": 0},
    {"id": 140, "question": "Which unit is used to measure noise levels?", "options": ["Decibel (dB)", "Watt", "Hertz", "Newton"], "correct": 0},
    {"id": 141, "question": "What noise level is generally considered the threshold for harmful noise?", "options": ["85 dB", "30 dB", "120 dB", "60 dB"], "correct": 0},
    {"id": 142, "question": "What does MSW stand for in waste management?", "options": ["Municipal Solid Waste", "Mixed Solid Waste", "Managed Solid Waste", "Medical Solid Waste"], "correct": 0},
    {"id": 143, "question": "Which type of waste is classified as hazardous?", "options": ["Chemical solvents", "Food waste", "Paper waste", "Plastic bottles"], "correct": 0},
    {"id": 144, "question": "The process of converting organic waste into nutrient-rich compost is called:", "options": ["Composting", "Incineration", "Landfilling", "Recycling"], "correct": 0},
    {"id": 145, "question": "What is leachate?", "options": ["Liquid formed when waste decomposes in a landfill", "A type of hazardous waste", "Solid waste material", "Gas produced during incineration"], "correct": 0},
    {"id": 146, "question": "Which international treaty deals with hazardous waste movement?", "options": ["Basel Convention", "Kyoto Protocol", "Montreal Protocol", "Paris Agreement"], "correct": 0},
    {"id": 147, "question": "Incineration of hazardous waste primarily helps in:", "options": ["Waste volume reduction", "Producing compost", "Groundwater recharge", "Increasing toxicity"], "correct": 0},
    {"id": 148, "question": "Which of the following is a solid waste segregation technique?", "options": ["Source separation", "Bulk dumping", "Open burning", "Leachate treatment"], "correct": 0},
    {"id": 149, "question": "Which hazardous waste treatment process involves heating waste in the absence of oxygen?", "options": ["Pyrolysis", "Incineration", "Composting", "Landfilling"], "correct": 0},
    {"id": 150, "question": "Which solid waste management method recovers energy from waste?", "options": ["Incineration", "Landfilling", "Composting", "Recycling"], "correct": 0},
    {"id": 151, "question": "Burning e-waste can release:", "options": ["Dioxins and furans", "Oxygen", "Carbon dioxide only", "Chlorofluorocarbons"], "correct": 0},
    {"id": 152, "question": "What is one of the most hazardous materials found in e-waste?", "options": ["Lead", "Plastic", "Glass", "Aluminium"], "correct": 0},
    {"id": 153, "question": "Which international standard is commonly used for OHASMS?", "options": ["ISO 45001", "ISO 9001", "ISO 27001", "ISO 14001"], "correct": 0},
    {"id": 154, "question": "The primary aim of OHASMS is to:", "options": ["Prevent workplace injuries and illnesses", "Improve product quality", "Manage environmental impact", "Increase production speed"], "correct": 0},
    {"id": 155, "question": "Which international event led to the celebration of World Environment Day?", "options": ["Stockholm Conference", "Rio Earth Summit", "Paris Agreement", "Kyoto Protocol"], "correct": 0},
    {"id": 156, "question": "Energy conservation refers to:", "options": ["Efficient and wise use of energy resources", "Using more energy", "Generating electricity using coal", "Avoiding renewable energy sources"], "correct": 0},
    {"id": 157, "question": "Energy efficiency means:", "options": ["Using less energy to perform the same task", "Using energy wastefully", "Using more energy than required", "Replacing energy with fuel"], "correct": 0},
    {"id": 158, "question": "Which device helps in energy conservation in homes?", "options": ["LED light", "Incandescent bulb", "Diesel generator", "Ceiling fan"], "correct": 0},
    {"id": 159, "question": "Which energy management technique involves studying energy usage patterns?", "options": ["Energy audit", "Billing system", "Fuel combustion", "Load shedding"], "correct": 0},
    {"id": 160, "question": "The energy conservation act in India was passed in:", "options": ["2001", "1995", "2010", "2005"], "correct": 0},
    {"id": 161, "question": "Which body is responsible for energy efficiency in India?", "options": ["BEE", "SEBI", "RBI", "ISRO"], "correct": 0},
    {"id": 162, "question": "Energy Star label on an appliance indicates:", "options": ["Energy efficiency", "Poor performance", "Low price", "Low warranty"], "correct": 0},
    {"id": 163, "question": "One unit of electricity is equal to:", "options": ["1 kilowatt-hour", "1 kilowatt", "1 watt", "1 megawatt"], "correct": 0},
    {"id": 164, "question": "Which of the following is a renewable energy source?", "options": ["Solar Energy", "Coal", "Natural Gas", "Nuclear Energy"], "correct": 0},
    {"id": 165, "question": "Which device is used to convert sunlight directly into electricity?", "options": ["Photovoltaic cell", "Wind turbine", "Hydroelectric dam", "Biomass generator"], "correct": 0},
    {"id": 166, "question": "Which gas is mainly responsible for the greenhouse effect?", "options": ["Carbon Dioxide", "Oxygen", "Nitrogen", "Helium"], "correct": 0},
    {"id": 167, "question": "Which renewable energy source is generated from organic matter?", "options": ["Biomass", "Solar", "Wind", "Hydropower"], "correct": 0},
    {"id": 168, "question": "Wind turbines convert:", "options": ["Kinetic energy into electricity", "Solar energy into electricity", "Heat energy into electricity", "Mechanical energy into heat"], "correct": 0},
    {"id": 169, "question": "Which is the cleanest renewable energy source?", "options": ["Solar", "Coal", "Natural Gas", "Oil"], "correct": 0},
    {"id": 170, "question": "What is biomass energy primarily derived from?", "options": ["Organic matter", "Fossil fuels", "Nuclear reactions", "Wind"], "correct": 0},
    {"id": 171, "question": "Which gas is produced during anaerobic digestion of biomass?", "options": ["Methane", "Oxygen", "Carbon dioxide", "Nitrogen"], "correct": 0},
    {"id": 172, "question": "Which process converts biomass into liquid biofuels?", "options": ["Fermentation", "Photosynthesis", "Gasification", "Combustion"], "correct": 0},
    {"id": 173, "question": "Bioethanol is mainly produced from:", "options": ["Corn and sugarcane", "Wood", "Coal", "Solar energy"], "correct": 0},
    {"id": 174, "question": "Which type of biomass energy technology produces heat and electricity directly by burning biomass?", "options": ["Combustion", "Anaerobic digestion", "Gasification", "Fermentation"], "correct": 0},
    {"id": 175, "question": "Biodiesel is mainly produced from:", "options": ["Vegetable oils and animal fats", "Coal", "Natural gas", "Wood"], "correct": 0},
    {"id": 176, "question": "Hydrogen fuel cells convert:", "options": ["Chemical energy into electricity", "Chemical energy directly into heat", "Electrical energy into mechanical energy", "Mechanical energy into chemical energy"], "correct": 0},
    {"id": 177, "question": "Electrolysis of water produces hydrogen and:", "options": ["Oxygen", "Nitrogen", "Carbon dioxide", "Methane"], "correct": 0},
    {"id": 178, "question": "What is a major challenge of using hydrogen as a fuel?", "options": ["Storage and transportation difficulties", "High carbon emissions", "Low energy content", "Limited fuel availability"], "correct": 0},
    {"id": 179, "question": "Which of the following is NOT a common method of hydrogen production?", "options": ["Combustion", "Electrolysis", "Steam methane reforming", "Biomass gasification"], "correct": 0},
    {"id": 180, "question": "Fuel cells require:", "options": ["Hydrogen and oxygen", "Constant supply of fossil fuels", "Nuclear fuel", "Coal"], "correct": 0},
    {"id": 181, "question": "Tidal barrages work similarly to:", "options": ["Hydroelectric dams", "Wind turbines", "Solar panels", "Geothermal plants"], "correct": 0},
    {"id": 182, "question": "Which country operates the largest tidal power station?", "options": ["South Korea", "United States", "Canada", "France"], "correct": 0},
    {"id": 183, "question": "Ocean energy is considered:", "options": ["Renewable", "Non-renewable", "Fossil fuel-based", "Polluting"], "correct": 0},
    {"id": 184, "question": "Which device is used to harness energy from ocean waves?", "options": ["Oscillating water column", "Pelton wheel", "Steam turbine", "Photovoltaic cells"], "correct": 0},
    {"id": 185, "question": "The unit used to measure tidal range is:", "options": ["Meters", "Kilowatts", "Joules", "Pascals"], "correct": 0},
    {"id": 186, "question": "Tidal energy is converted into electricity using:", "options": ["Turbines", "Solar panels", "Gas engines", "Batteries"], "correct": 0},
    {"id": 187, "question": "The height difference between high tide and low tide is called:", "options": ["Tide range", "Wave height", "Tidal flow", "Tidal speed"], "correct": 0},
    {"id": 188, "question": "What is the primary source of geothermal energy?", "options": ["Heat from Earth's interior", "Sunlight", "Ocean currents", "Wind movement"], "correct": 0},
    {"id": 189, "question": "Which of the following best describes the source of geothermal energy?", "options": ["Radioactive decay of materials in Earth's core", "Photosynthesis", "Ocean waves", "Burning of coal"], "correct": 0},
    {"id": 190, "question": "The first commercial geothermal power plant was established in:", "options": ["1904", "1864", "1950", "1975"], "correct": 0},
    {"id": 191, "question": "Which layer of the Earth is the hottest and contributes most to geothermal heat?", "options": ["Inner core", "Crust", "Mantle", "Outer core"], "correct": 0},
    {"id": 192, "question": "What type of rock is typically associated with geothermal activity?", "options": ["Igneous", "Sedimentary", "Metamorphic", "Limestone"], "correct": 0},
    {"id": 193, "question": "Geothermal energy is found most abundantly in:", "options": ["Volcanic regions and tectonic plate boundaries", "Desert areas", "Coastal regions", "High-altitude mountains"], "correct": 0},
    {"id": 194, "question": "The transfer of geothermal heat from the Earth's interior to the surface is primarily through:", "options": ["Convection", "Radiation", "Conduction", "Evaporation"], "correct": 0},
    {"id": 195, "question": "Which radioactive elements are mainly responsible for geothermal heat?", "options": ["Uranium, thorium, and potassium", "Iron, carbon, and silicon", "Nitrogen, oxygen, and argon", "Sodium, chlorine, and magnesium"], "correct": 0},
    {"id": 196, "question": "In which of the Earth's layers is geothermal energy stored?", "options": ["Lithosphere", "Atmosphere", "Hydrosphere", "Exosphere"], "correct": 0}
]

print(f"Questions 101-196: {len(ess_questions_101_196)}")

# Combine all questions
all_ess_questions = ess_questions + ess_questions_51_100 + ess_questions_101_196
print(f"Total ESS questions: {len(all_ess_questions)}")

# Verify question IDs are sequential
question_ids = [q['id'] for q in all_ess_questions]
print(f"Question IDs range from {min(question_ids)} to {max(question_ids)}")
print(f"All questions have 4 options: {all(len(q['options']) == 4 for q in all_ess_questions)}")
print(f"All correct answers are 0: {all(q['correct'] == 0 for q in all_ess_questions)}")

print("✅ All 196 ESS questions extracted successfully!")